POST http://localhost:3020/api/user/login
Content-Type: application/json

{
    "user_name": "Admin",
    "password": "12345"
}

###

POST http://localhost:3020/api/table/susses_table
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZnVsbF9uYW1lIjoiTmd1eeG7hW4gxJDDrG5oIENodcOibiIsImF2YXRhciI6Imh0dHA6Ly9sb2NhbGhvc3Q6MzAyMC91cGxvYWQvdXNlci9oaW5oLWFuaC1naXJsLXhpbmgtdG9jLW5nYW4tZGUtdGh1b25nLmpwZyIsInJvbGUiOjEsImlhdCI6MTY2ODQyMjgwNCwiZXhwIjoxNjcwMDkxMzE0MDE2fQ.4tJQ60ptVdlMg_HzjJIT-MZ4OC9QD-2p1hWkZCXC8-k
Content-Type: application/json

{
    "user_name": "Admin",
    "password": "12345"
}

###

GET  http://localhost:3020/api/news/details_news/35
###

GET http://localhost:3020/api/news/search_tag_news/khuyen-mai-lau-wang/12/1

###

DELETE http://localhost:3020/api/table/cancel_order/26
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6MSwiYXZhdGFyIjoiaHR0cDovL2xvY2FsaG9zdDozMDIwL3VwbG9hZC91c2VyL3VuZGVmaW5lZCIsImlhdCI6MTY2OTA4ODc1NCwiZXhwIjoxNjcwODQ0MjQyOTYyfQ.QyDvkjHV6tCZRMTFLw8QiZnMa7bsPTf9HlGIeA5MpoM

###

GET http://localhost:3020/api/table/list_table_pay/1/1/10/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZnVsbF9uYW1lIjoiTmd1eeG7hW4gxJDDrG5oIENodcOibiIsImF2YXRhciI6Imh0dHA6Ly9sb2NhbGhvc3Q6MzAyMC91cGxvYWQvdXNlci9oaW5oLWFuaC1naXJsLXhpbmgtdG9jLW5nYW4tZGUtdGh1b25nLmpwZyIsInJvbGUiOjEsImlhdCI6MTY2ODQyMjgwNCwiZXhwIjoxNjcwMDkxMzE0MDE2fQ.4tJQ60ptVdlMg_HzjJIT-MZ4OC9QD-2p1hWkZCXC8-k